services:
  backend:
    build: ./backend
    container_name: cjr-backend
    env_file:
      - ./backend/.env
    depends_on:
      - db

  nginx:
    build: ./frontend
    container_name: cjr-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: cjr-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: czech_jump_rope
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d/

volumes:
  db_data: