services:
  backend:
    build: ./backend
    container_name: cjr-backend
    ports:
      - "3001:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: cjr-frontend
    ports:
      - "5174:5173"
#    environment:
#      - VITE_API_URL=http://cjr-backend:3001/api
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: cjr-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: czech_jump_rope
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d/

volumes:
  db_data:
